name: Release Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker
        shell: bash
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Images
        shell: bash
        run: |
          export TAG=$(date -u +"%FT%H-%M-%SUTC")
          docker build -t yriahi/semantic-release-image:latest .
          docker tag yriahi/semantic-release-image:latest yriahi/semantic-release-image:$TAG
          docker push yriahi/semantic-release-image:latest
          docker push yriahi/semantic-release-image:$TAG
